<?php

/**                                                                                                                                                           
 * @file                                                                                                                                                      
 * A module that defines the excuses, excuses core functionality and various helper functions.                                                                        
 */
